Asociados/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView  # Nico 14/11/2024

urlpatterns = [
    path('', include('public.urls')),  
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),  # Nico 15/11/2024 app personalizada para agragar sign up que no viene en las librerias estándares
    path("accounts/", include("django.contrib.auth.urls")), # Nico 14/11/2024
    path('Nomina/', include('Nomina.urls')),
    path('Liquidacion/', include('Liquidacion.urls')),
    path('Dashboards/', include('Dashboards.urls')),
]

Liquidacion/urls.py
from django.urls import path
from Liquidacion import views

urlpatterns = [
    path('liquidacion-list', views.liquidacion_list, name="LiquidacionList"),
    path('liquidacion-read/<int:liquidacion_id>/', views.liquidacion_read, name="LiquidacionRead"),
]

Nomina/urls.py
from django.urls import path
from Nomina import views

urlpatterns = [
    path('afiliado-list', views.afiliado_list, name="AfiliadoList"),
    path('afiliado-create', views.afiliado_create, name="AfiliadoCreate"),
    path('afiliado-update/<int:afiliado_id>/', views.afiliado_update, name="AfiliadoUpdate"),
    path('afiliado-baja/<int:afiliado_id>/', views.afiliado_baja, name="AfiliadoBaja"),
]

Liquidacion/models.py
from django.db import models
from Nomina.models import Empresa, Afiliado

# Create your models here.
class LiquidacionCabecera(models.Model):
    comprobante = models.CharField(max_length=2)
    letra = models.CharField(max_length=1)
    sucursal = models.CharField(max_length=1)
    numero = models.CharField(max_length=10)
    fecha = models.DateField()
    tipo_deudor = models.CharField(max_length=6)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, blank=True, null=True)
    condicion = models.CharField(max_length=6) #condición de pago
    moneda = models.CharField(max_length=5)
    estado = models.CharField(max_length=1)
    gravada = models.CharField(max_length=1)
    periodo = models.CharField(max_length=10)
    vencimiento = models.DateField()
    cantidad_afiliados = models.IntegerField()
    total_liquidado = models.DecimalField(max_digits=12, decimal_places=2)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        sc = str(self.empresa.codigo) + ' - ' + self.empresa.nombre_fantasia + ' - ' + str(self.periodo)
        return sc

class LiquidacionDetalle(models.Model):
    secuencia = models.CharField(max_length=2)
    concepto_codigo = models.CharField(max_length=5)
    concepto_descripcion = models.CharField(max_length=50)
    cantidad = models.IntegerField()
    precio_unitario = models.DecimalField(max_digits=12, decimal_places=2)
    liquidacion = models.ForeignKey('LiquidacionCabecera', on_delete=models.CASCADE, blank=True, null=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        sc = str(self.liquidacion.empresa.codigo) + ' - ' + self.secuencia + ' - ' + str(self.concepto_descripcion)
        return sc

    def subtotal(self):
        st = self.cantidad * self.precio_unitario
        return st

Liquidacion/views.py
from django.shortcuts import render, get_object_or_404
from .models import LiquidacionCabecera, LiquidacionDetalle
from django.core.paginator import Paginator
from Asociados.utils import IdEmpresaActiva

# Create your views here.
def liquidacion_list(request):    
    # Obtener la lista de liquidaciones
    liqs = LiquidacionCabecera.objects.filter(empresa__id = IdEmpresaActiva()).order_by("-fecha")[:12]
    
    # Configurar el paginador
    np = 20 # Definir el nro de liquidaciones por página
    paginator = Paginator(liqs, np)  # Show "np" liqs per page.
    # Obtener el número de página desde los parámetros GET
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    ru2 = page_obj.number + 2
    rd2 = page_obj.number - 2
    rd3 = page_obj.number - 3
    ru3 = page_obj.number + 3

    return render(request, "liquidacion/liquidacion_l.html", {"page_obj": page_obj,  
                                           "ru2":ru2,
                                           "rd2":rd2,
                                           "rd3":rd3,
                                           "ru3":ru3})

def liquidacion_read(request, liquidacion_id):
    lC = get_object_or_404(LiquidacionCabecera, id=liquidacion_id)
    lD = LiquidacionDetalle.objects.filter(liquidacion_id = liquidacion_id).order_by("secuencia")
    return render(request, 'liquidacion/liquidacion_r.html', {'cabecera': lC, 'detalle': lD})

Liquidacion/templates/liquidacion/liquidacion_l.html
{% extends "base.html" %}
{% load static %}
{% block title %}Asociados APROSS - Liquidaci&oacute;n{% endblock %}
{% block page-breadcrumb %}Liquidaci&oacute;n{% endblock %}
{% block page-title %}Liquidaciones{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-12">
      <div class="card mb-4">
        <div class="card-header pb-0">
          <div class="d-flex">            
            <h6>Liquidaciones</h6>  
          </div>
        </div>
        <div class="card-body px-0 pt-0 pb-2">
          <div class="table-responsive p-0">
            <table class="table align-items-center mb-0">
              <thead>
                <tr>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Per&iacute;odo / Comprobante</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Fecha</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Vencimiento</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-1">Nomina</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Total</th>
                </tr>
              </thead>
              <tbody>                  
                {% for liquidacion in page_obj %}
                <tr>
                  <td>
                    <div class="d-flex px-2 py-1">
                        <a href="{% url 'LiquidacionRead' liquidacion.id %}">
                            <div class="icon icon-shape icon-sm me-3 bg-gradient-success shadow text-center">
                                <i class="ni ni-tag text-white opacity-10"></i>
                            </div>
                        </a>
                        <div class="d-flex flex-column justify-content-center">
                            <h6 class="mb-0 text-sm"><a href="{% url 'LiquidacionRead' liquidacion.id %}">{{liquidacion.periodo}}</a></h6>
                            <p class="text-xs text-secondary mb-0"><a href="{% url 'LiquidacionRead' liquidacion.id %}">{{liquidacion.comprobante}}-{{liquidacion.letra}}-{{liquidacion.sucursal}}-{{liquidacion.numero}}</a></p>
                        </div>
                    </div>
                  </td>
                  <td>
                    <p class="text-xs font-weight-bold mb-0">{{liquidacion.fecha}}</p>
                  </td>
                  <td>
                    <p class="text-xs font-weight-bold mb-0">{{liquidacion.vencimiento}}</p>
                  </td>
                  <td>
                    <p class="text-xs font-weight-bold mb-0">{{liquidacion.cantidad_afiliados}}</p>
                  </td>
                  <td>
                    <p class="text-xs font-weight-bold mb-0">{{liquidacion.total_liquidado}}</p>
                  </td>
                </tr>
                {% endfor %}
                
              </tbody>
            </table>
          </div>
          <!-- INICIO PAGINACION -->
          {% if page_obj.has_other_pages %}
          <div class="ct-example" style="position: relative;border: 2px solid #f5f7ff !important;border-bottom: none !important;padding: 1rem 1rem 2rem 1rem;margin-bottom: -1.25rem;">
            <nav aria-label="...">
            <div class="pagination-container justify-content-center">
            <ul class="pagination pagination-success">
              {% if page_obj.number > 1 %}
              <li class="page-item">
                <a class="page-link" href="?page=1" aria-label="Primera">
                  <span aria-hidden="true"><i class="fa fa-angle-double-left" aria-hidden="true"></i></span>
                </a>
              </li>
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Anterior">
                  <span aria-hidden="true"><i class="fa fa-angle-left" aria-hidden="true"></i></span>
                </a>
              </li>
              {% endif %}

              {# Mostrar las páginas #}
              {% for i in page_obj.paginator.page_range %}
                  {% if i == page_obj.number %}
                  <li class="page-item active">
                    <a class="page-link" href="javascript:;" style="color: #fff;">{{ i }} <span class="sr-only">(current)</span></a>
                  </li>
                  {% elif i == 1 or i == page_obj.paginator.num_pages or i >= rd2 and i <= ru2 %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ i }}">{{ i }}</a> {# Otras páginas #}
                  </li>
                  {% elif i == rd3 or i == ru3 %}
                  <li class="page-item disabled">
                    <a class="page-link" href="javascript:;">...</a> {# Abreviación #}
                  </li>
                  {% endif %}
              {% endfor %}

              {% if page_obj.has_next %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Siguiente">
                    <span aria-hidden="true"><i class="fa fa-angle-right" aria-hidden="true"></i></span>
                  </a>
                </li>
                <li class="page-item">
                  <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Última">
                    <span aria-hidden="true"><i class="fa fa-angle-double-right" aria-hidden="true"></i></span>
                  </a>
                </li>
              {% endif %}
            </ul>
            </div>
            </nav>
          </div>
          {% endif %}
          <!-- FIN PAGINACION -->
        </div>      
      </div>
    </div>
  </div>
  {% endblock %}

Liquidacion/templates/liquidacion/liquidacion_r.html
{% extends "base.html" %}
{% load static %}
{% block title %}Asociados APROSS - Liquidaci&oacute;n{% endblock %}
{% block page-breadcrumb %}Liquidaci&oacute;n{% endblock %}
{% block page-title %}Liquidaciones{% endblock %}

{% block content %}

<!-- Afiliado Create: afiliado_c.html -->
<div class="row">
    <div class="col-12">
        <div class="card mb-4">
            <div class="card-header pb-0">
                <h6>Liquidaci&oacute;n</h6>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="id_periodo">Periodo:</label>
                            <input type="text" name="periodo" value="{{ cabecera.periodo }}" class="form-control form-control-sm" disabled="disabled" id="id_periodo">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="id_comprobante">Comprobante:</label>
                            <input type="text" name="comprobante" value="{{cabecera.comprobante}}-{{cabecera.letra}}-{{cabecera.sucursal}}-{{cabecera.numero}}" class="form-control form-control-sm" disabled="disabled" id="id_comprobante">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="id_fecha">Fecha:</label>
                            <input type="text" name="fecha" value="{{cabecera.fecha}}" class="form-control form-control-sm" disabled="disabled" id="id_fecha">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="id_vencimiento">Vencimiento:</label>
                            <input type="text" name="vencimiento" value="{{cabecera.vencimiento}}" class="form-control form-control-sm" disabled="disabled" id="id_vencimiento">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="id_condicion">Condicion:</label>
                            <input type="text" name="condicion" value="{{ cabecera.condicion }}" class="form-control form-control-sm" disabled="disabled" id="id_condicion">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="id_moneda">Moneda:</label>
                            <input type="text" name="moneda" value="{{cabecera.moneda}}" class="form-control form-control-sm" disabled="disabled" id="id_moneda">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="id_estado">Estado:</label>
                            <input type="text" name="estado" value="{{cabecera.estado}}" class="form-control form-control-sm" disabled="disabled" id="id_estado">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="id_tipo_deudor">Tipo:</label>
                            <input type="text" name="tipo_deudor" value="{{cabecera.tipo_deudor}}" class="form-control form-control-sm" disabled="disabled" id="id_tipo_deudor">
                        </div>
                    </div>
                </div>
                <div class="table-responsive p-0">
                    <table class="table mb-0">
                        <thead>
                            <tr>
                                <th class="text-start text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Secuencia</th>
                                <th class="text-start text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Cod.</th>
                                <th class="text-start text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Concepto</th>
                                <th class="text-end text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Cantidad</th>
                                <th class="text-end text-uppercase text-secondary text-xxs text-end font-weight-bolder opacity-7">Precio Unitario</th>
                                <th class="text-end text-uppercase text-secondary text-xxs text-end font-weight-bolder opacity-7">Subtotal</th>
                            </tr>
                        </thead>
                        <tbody>                                          
                        {% for linea in detalle %}
                            <tr>
                                <td><p class="text-xs font-weight-bold mb-0">{{ linea.secuencia }}</p></td>
                                <td><p class="text-xs font-weight-bold mb-0">{{ linea.concepto_codigo }}</p></td>
                                <td><p class="text-xs font-weight-bold mb-0">{{ linea.concepto_descripcion }}</p></td>
                                <td><p class="text-end text-xs font-weight-bold mb-0">{{ linea.cantidad }}</p></td>
                                <td><p class="text-end text-xs font-weight-bold mb-0">{{ linea.precio_unitario }}</p></td>
                                <td><p class="text-end text-xs font-weight-bold mb-0">{{ linea.subtotal }}</p></td>
                            </tr>
                        {% endfor %}                 
                            <tr>
                                <td><p class="text-xs font-weight-bold mb-0">&nbsp;</p></td>
                                <td><p class="text-xs font-weight-bold mb-0">&nbsp;</p></td>
                                <td><p class="text-xs font-weight-bold mb-0">&nbsp;</p></td>
                                <td><p class="text-end text-sm font-weight-bold mb-0">{{ cabecera.cantidad_afiliados }}</p></td>
                                <td><p class="text-end text-xs font-weight-bold mb-0">&nbsp;</p></td>
                                <td><p class="text-end text-sm font-weight-bold mb-0">{{ cabecera.total_liquidado }}</p></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="text-center">
                    <a class="btn btn-sm bg-gradient-default btn-lg mt-4 mb-0" href="{% url 'LiquidacionList' %}">Cancelar</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}